##################################
# Amazon - example configuration #
##################################

# Amazon component configuration requires the registraion of dependant libraries with ClassLoader.
# If you use Composer, then you don't need to register the libraries with ClassLoader.
# Currently only S3 cloud storage is supported within this component, and we need to define our S3 bridge
# that communicates with Amazon S3
Amazon:
    S3:
        # You can overwrite the default driver by providing your own.
        # How to create a new driver, read in the Readme.md file.
        # If you don't wish to change the default driver,
        # just ommit this definition in your config file.
        Bridge:  \Webiny\Component\Amazon\Bridge\S3\S3